package testutils

import (
	"github.com/bufbuild/protocompile/protoutil"
	"github.com/go-errors/errors"
	"github.com/jhump/protoreflect/v2/protobuilder"
	"github.com/jhump/protoreflect/v2/protoprint"
	"github.com/jhump/protoreflect/v2/sourceinfo"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"

	_ "google.golang.org/protobuf/types/known/anypb"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/structpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	wktsPaths = map[string]string{
		// TODO: handle more Well-Known proto types
		"google.protobuf.Timestamp":   "google/protobuf/timestamp.proto",
		"google.protobuf.Empty":       "google/protobuf/empty.proto",
		"google.protobuf.Int32Value":  "google/protobuf/wrappers.proto",
		"google.protobuf.Int64Value":  "google/protobuf/wrappers.proto",
		"google.protobuf.UInt32Value": "google/protobuf/wrappers.proto",
		"google.protobuf.UInt64Value": "google/protobuf/wrappers.proto",
		"google.protobuf.FloatValue":  "google/protobuf/wrappers.proto",
		"google.protobuf.DoubleValue": "google/protobuf/wrappers.proto",
		"google.protobuf.StringValue": "google/protobuf/wrappers.proto",
		"google.protobuf.BoolValue":   "google/protobuf/wrappers.proto",
		"google.protobuf.BytesValue":  "google/protobuf/wrappers.proto",
		"google.protobuf.Struct":      "google/protobuf/struct.proto",
		"google.protobuf.ListValue":   "google/protobuf/struct.proto",
		"google.protobuf.Value":       "google/protobuf/struct.proto",
		"google.protobuf.Duration":    "google/protobuf/duration.proto",
	}
	wktsPathsList = make([]string, 0, len(wktsPaths))
)

func init() {
	for _, v := range wktsPaths {
		wktsPathsList = append(wktsPathsList, v)
	}
}

func DumpMessageDescriptors(dpbMessages []*descriptorpb.DescriptorProto) (string, error) {
	fd := &descriptorpb.FileDescriptorProto{
		Syntax:      ptr("proto3"),
		Name:        ptr("dummy.proto"),
		Package:     ptr("testpkg"),
		MessageType: dpbMessages,
		Dependency: []string{
			"google/protobuf/wrappers.proto",
			"google/protobuf/struct.proto",
			"google/protobuf/timestamp.proto",
			"google/protobuf/empty.proto",
			"google/protobuf/duration.proto",
		},
	}

	res, err := DumpFileDescriptors([]*descriptorpb.FileDescriptorProto{fd})
	if err != nil {
		return "", err
	}
	if res["dummy.proto"] == "" {
		return "", errors.New("entproto: failed dumping message descriptors")
	}
	return res["dummy.proto"], nil
}

func DumpFileDescriptors(dpbDescriptors []*descriptorpb.FileDescriptorProto) (map[string]string, error) {
	descriptors := make(map[string]protoreflect.FileDescriptor)
	dpbDescriptors = DedupeFileDescriptors(dpbDescriptors)

	for _, wktPath := range wktsPaths {
		typeDesc, err := sourceinfo.Files.FindFileByPath(wktPath)
		if err != nil {
			return nil, errors.Errorf("entproto: failed finding wkt file descriptor for %q: %w", wktPath, err)
		}
		dpbDescriptors = append(dpbDescriptors, protoutil.ProtoFromFileDescriptor(typeDesc))
	}

	dpbDescriptors = DedupeFileDescriptors(dpbDescriptors)

	fds, err := protodesc.NewFiles(&descriptorpb.FileDescriptorSet{
		File: dpbDescriptors,
	})
	if err != nil {
		return nil, errors.Errorf("entproto: failed creating file descriptors: %w", err)
	}

	var rangeErr error
	fds.RangeFiles(func(fd protoreflect.FileDescriptor) bool {
		fbuild, err := protobuilder.FromFile(fd)
		if err != nil {
			rangeErr = errors.Errorf("entproto: failed building file descriptor for %q: %w", fd.Path(), err)
			return false
		}
		fbuild.SetSyntaxComments(protobuilder.Comments{
			LeadingComment: " Code generated by entproto. DO NOT EDIT.",
		})
		fd, err = fbuild.Build()
		if err != nil {
			rangeErr = errors.Errorf("entproto: failed building file descriptor for %q: %w", fd.Path(), err)
			return false
		}
		descriptors[string(fd.Path())] = fd
		return true
	})
	if rangeErr != nil {
		return nil, rangeErr
	}

	for _, wktPath := range wktsPathsList {
		delete(descriptors, wktPath)
	}

	printer := &protoprint.Printer{}

	results := make(map[string]string, len(descriptors))

	for _, fd := range descriptors {
		s, err := printer.PrintProtoToString(fd)
		if err != nil {
			return nil, errors.Errorf("entproto: failed printing proto file %q: %w", fd.Path(), err)
		}
		results[fd.Path()] = s
	}

	return results, nil
}

func DedupeFileDescriptors(fds []*descriptorpb.FileDescriptorProto) []*descriptorpb.FileDescriptorProto {
	seen := make(map[string]struct{})
	var out []*descriptorpb.FileDescriptorProto
	for _, fd := range fds {
		if _, ok := seen[fd.GetName()]; !ok {
			out = append(out, fd)
			seen[fd.GetName()] = struct{}{}
		}
	}
	return out
}

func ptr[T any](v T) *T {
	return &v
}
