// Code generated by protoc-gen-entgrpc. DO NOT EDIT.
package entpbservice

import (
	connect "connectrpc.com/connect"
	context "context"
	gen "entgo.io/ent/entc/gen"
	ent "github.com/yoshino-s/entproto/internal/test/ent"
	user "github.com/yoshino-s/entproto/internal/test/ent/user"
	entpb "github.com/yoshino-s/entproto/internal/test/proto/entpb"
	entpbconnect "github.com/yoshino-s/entproto/internal/test/proto/entpb/entpbconnect"
	runtime "github.com/yoshino-s/entproto/runtime"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// UserServiceHandler implements $connectHandler
type UserServiceHandler struct {
	*runtime.BaseService
	*ent.Client
}

var _ entpbconnect.UserServiceHandler = (*UserServiceHandler)(nil)

// NewUserServiceHandler returns a new UserServiceHandler
func NewUserServiceHandler(client *ent.Client) *UserServiceHandler {
	return &UserServiceHandler{
		BaseService: runtime.NewBaseService(),
		Client:      client,
	}
}

// Create implements UserServiceHandlerServer.Create
func (svc *UserServiceHandler) Create(ctx context.Context, req *connect.Request[entpb.User]) (*connect.Response[entpb.User], error) {
	user := req.Msg
	m, err := svc.createBuilder(user)
	if err != nil {
		return nil, err
	}

	if err := svc.RunHooks(ctx, runtime.ActionCreate, req, m); err != nil {
		return nil, err
	}

	return runtime.WrapResult(WrapProtoUser(m.Save(ctx)))

}

// Get implements UserServiceHandlerServer.Get
func (svc *UserServiceHandler) Get(ctx context.Context, req *connect.Request[wrapperspb.Int32Value]) (*connect.Response[entpb.User], error) {

	query := svc.Client.User.Query()
	query = query.Where(
		user.ID(int(req.Msg.Value)),
	)

	if err := svc.RunHooks(ctx, runtime.ActionGet, req, query); err != nil {
		return nil, err
	}
	return runtime.WrapResult(WrapProtoUser(query.First(ctx)))

}

// Update implements UserServiceHandlerServer.Update
func (svc *UserServiceHandler) Update(ctx context.Context, req *connect.Request[entpb.User]) (*connect.Response[entpb.User], error) {
	user := req.Msg
	userID := int(user.GetId())
	m := svc.Client.User.UpdateOneID(userID)
	if user.GetDescription() != nil {
		userDescription := user.GetDescription().GetValue()
		m.SetDescription(userDescription)
	}
	userGender := toEntUser_Gender(user.GetGender())
	m.SetGender(userGender)
	if user.GetGroupId() != nil {
		userGroupID := int(user.GetGroupId().GetValue())
		m.SetGroupID(userGroupID)
	}
	userName := user.GetName()
	m.SetName(userName)
	if user.GetGroup() != nil {
		userGroup := int(user.GetGroup().GetId())
		m.SetGroupID(userGroup)
	}

	if err := svc.RunHooks(ctx, runtime.ActionUpdate, req, m); err != nil {
		return nil, err
	}

	return runtime.WrapResult(WrapProtoUser(m.Save(ctx)))

}

// Delete implements UserServiceHandlerServer.Delete
func (svc *UserServiceHandler) Delete(ctx context.Context, req *connect.Request[wrapperspb.Int32Value]) (*connect.Response[emptypb.Empty], error) {

	query := svc.Client.User.DeleteOneID(int(req.Msg.Value))
	if err := svc.RunHooks(ctx, runtime.ActionDelete, req, query); err != nil {
		return nil, err
	}

	if err := query.Exec(ctx); err != nil {
		return nil, wrapError(err)
	}
	return connect.NewResponse(&emptypb.Empty{}), nil

}

// List implements UserServiceHandlerServer.List
func (svc *UserServiceHandler) List(ctx context.Context, req *connect.Request[entpb.ListUserRequest]) (*connect.Response[entpb.ListUserResponse], error) {

	query, totalQuery, err := svc.BuildListQuery(ctx, req)

	if err != nil {
		return nil, wrapError(err)
	}

	items, err := WrapProtoUserList(query.All(ctx))
	if err != nil {
		return nil, wrapError(err)
	}
	total, err := totalQuery.Count(ctx)
	if err != nil {
		return nil, wrapError(err)
	}

	return connect.NewResponse(&entpb.ListUserResponse{
		Items: items,
		Total: int32(total),
	}), nil

}

// List implements UserServiceHandlerServer.List
func (svc *UserServiceHandler) BuildListQuery(ctx context.Context, req *connect.Request[entpb.ListUserRequest]) (*ent.UserQuery, *ent.UserQuery, error) {

	snake := gen.Funcs["snake"].(func(string) string)

	query := svc.Client.User.Query()
	totalQuery := svc.Client.User.Query()

	if !req.Msg.NoLimit {
		if req.Msg.Limit != nil && req.Msg.Limit.Value > 0 {
			query = query.Limit(int(req.Msg.Limit.Value))
		} else { // If no limit, set default limit
			query = query.Limit(10)
		}
	}
	if req.Msg.Offset != nil {
		query = query.Offset(int(req.Msg.Offset.Value))
	}
	if req.Msg.Order != nil {
		OrderFunc := ent.Asc
		if req.Msg.Descending {
			OrderFunc = ent.Desc
		}
		query = query.Order(OrderFunc(snake(req.Msg.Order.Value)))
	} else {
		query = query.Order(ent.Asc("id"))
	}

	if req.Msg.Filter != nil {
	}

	if err := svc.RunHooks(ctx, runtime.ActionList, req, query); err != nil {
		return nil, nil, err
	}
	if err := svc.RunHooks(ctx, runtime.ActionListCount, req, totalQuery); err != nil {
		return nil, nil, err
	}

	return query, totalQuery, nil

}

func (svc *UserServiceHandler) createBuilder(user *entpb.User) (*ent.UserCreate, error) {
	m := svc.Client.User.Create()
	userCreatedAt := runtime.ExtractTime(user.GetCreatedAt())
	m.SetCreatedAt(userCreatedAt)
	if user.GetDescription() != nil {
		userDescription := user.GetDescription().GetValue()
		m.SetDescription(userDescription)
	}
	userGender := toEntUser_Gender(user.GetGender())
	m.SetGender(userGender)
	if user.GetGroupId() != nil {
		userGroupID := int(user.GetGroupId().GetValue())
		m.SetGroupID(userGroupID)
	}
	userName := user.GetName()
	m.SetName(userName)
	if user.GetGroup() != nil {
		userGroup := int(user.GetGroup().GetId())
		m.SetGroupID(userGroup)
	}
	return m, nil
}
