// Code generated by protoc-gen-entgrpc. DO NOT EDIT.
package entpbservice

import (
	connect "connectrpc.com/connect"
	sqlgraph "entgo.io/ent/dialect/sql/sqlgraph"
	errors "github.com/go-errors/errors"
	ent "github.com/yoshino-s/entproto/internal/test/ent"
	_ "github.com/yoshino-s/entproto/internal/test/proto/entpb"
)

func wrapError(err error) error {
	switch {
	case err == nil:
		return nil
	case ent.IsNotFound(err):
		return connect.NewError(connect.CodeNotFound, errors.Errorf("not found: %s", err))
	case sqlgraph.IsUniqueConstraintError(err):
		return connect.NewError(connect.CodeAlreadyExists, errors.Errorf("already exists: %s", err))
	case ent.IsConstraintError(err):
		return connect.NewError(connect.CodeInvalidArgument, errors.Errorf("invalid argument: %s", err))
	default:
		return connect.NewError(connect.CodeInternal, errors.Errorf("internal error: %s", err))
	}
}
