// Code generated by protoc-gen-entgrpc. DO NOT EDIT.
package entpbservice

import (
	connect "connectrpc.com/connect"
	errors "github.com/go-errors/errors"
	ent "github.com/yoshino-s/entproto/internal/test/ent"
	user "github.com/yoshino-s/entproto/internal/test/ent/user"
	entpb "github.com/yoshino-s/entproto/internal/test/proto/entpb"
	runtime "github.com/yoshino-s/entproto/runtime"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	regexp "regexp"
	strings "strings"
)

var protoIdentNormalizeRegexpUser_Gender = regexp.MustCompile(`[^a-zA-Z0-9_]+`)

func protoIdentNormalizeUser_Gender(e string) string {
	return protoIdentNormalizeRegexpUser_Gender.ReplaceAllString(e, "_")
}

func toProtoUser_Gender(e user.Gender) entpb.User_Gender {
	if v, ok := entpb.User_Gender_value[strings.ToUpper("GENDER_"+protoIdentNormalizeUser_Gender(string(e)))]; ok {
		return entpb.User_Gender(v)
	}
	return entpb.User_Gender(0)
}

func toEntUser_Gender(e entpb.User_Gender) user.Gender {
	if v, ok := entpb.User_Gender_name[int32(e)]; ok {
		entVal := map[string]string{
			"GENDER_MALE":   "male",
			"GENDER_FEMALE": "female",
		}[v]
		return user.Gender(entVal)
	}
	return ""
}

// ToProtoUser transforms the ent type to the pb type
func ToProtoUser(e *ent.User) (*entpb.User, error) {
	v := &entpb.User{}
	created_at := timestamppb.New(e.CreatedAt)
	v.CreatedAt = created_at
	description := wrapperspb.String(e.Description)
	v.Description = description
	gender := toProtoUser_Gender(e.Gender)
	v.Gender = gender
	group := wrapperspb.Int32(int32(e.GroupID))
	v.GroupId = group
	id := int32(e.ID)
	v.Id = id
	name := e.Name
	v.Name = name
	preferences, err := ConvertStringAnyMapToProto(e.Preferences)
	if err != nil {
		return nil, err
	}
	v.Preferences = preferences
	if edg := e.Edges.Group; edg != nil {
		x, err := ToProtoGroup(edg)
		if err != nil {
			return nil, err
		}
		v.Group = x
	}
	return v, nil
}

func WrapProtoUser(e *ent.User, err error) (*entpb.User, error) {
	if err == nil {
		return ToProtoUser(e)
	}
	return nil, wrapError(err)
}

// ToProtoUserList transforms a list of ent type to a list of pb type
func ToProtoUserList(e []*ent.User) ([]*entpb.User, error) {
	var pbList []*entpb.User
	for _, entEntity := range e {
		pbEntity, err := ToProtoUser(entEntity)
		if err != nil {
			return nil, connect.NewError(connect.CodeInternal, errors.Errorf("internal error: %s", err))
		}
		pbList = append(pbList, pbEntity)
	}
	return pbList, nil
}

func WrapProtoUserList(e []*ent.User, err error) ([]*entpb.User, error) {
	if err == nil {
		return ToProtoUserList(e)
	}
	return nil, wrapError(err)
}

// ExtraConverts
func ConvertProtoToStringAnyMap(in map[string]*structpb.Value) (map[string]any, error) {
	result := make(map[string]any)
	for key, value := range in {
		var valueTmpObj any
		valueErr := runtime.FromStructPbValue(value, &valueTmpObj)
		if valueErr != nil {
			return nil, valueErr
		}
		result[key] = valueTmpObj
	}
	return result, nil
}

func ConvertStringAnyMapToProto(in map[string]any) (map[string]*structpb.Value, error) {
	result := make(map[string]*structpb.Value)
	for key, value := range in {
		valueTmpObj, valueErr := runtime.ToStructPbValue(value)
		if valueErr != nil {
			return nil, valueErr
		}
		result[key] = valueTmpObj
	}
	return result, nil
}
