// Code generated by protoc-gen-entgrpc. DO NOT EDIT.
package entpbservice

import (
	connect "connectrpc.com/connect"
	context "context"
	gen "entgo.io/ent/entc/gen"
	ent "github.com/yoshino-s/entproto/internal/test/ent"
	group "github.com/yoshino-s/entproto/internal/test/ent/group"
	entpb "github.com/yoshino-s/entproto/internal/test/proto/entpb"
	entpbconnect "github.com/yoshino-s/entproto/internal/test/proto/entpb/entpbconnect"
	runtime "github.com/yoshino-s/entproto/runtime"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// GroupServiceHandler implements $connectHandler
type GroupServiceHandler struct {
	*runtime.BaseService
	*ent.Client
}

var _ entpbconnect.GroupServiceHandler = (*GroupServiceHandler)(nil)

// NewGroupServiceHandler returns a new GroupServiceHandler
func NewGroupServiceHandler(client *ent.Client) *GroupServiceHandler {
	return &GroupServiceHandler{
		BaseService: runtime.NewBaseService(),
		Client:      client,
	}
}

// Create implements GroupServiceHandlerServer.Create
func (svc *GroupServiceHandler) Create(ctx context.Context, req *connect.Request[entpb.Group]) (*connect.Response[entpb.Group], error) {
	group := req.Msg
	m, err := svc.createBuilder(group)
	if err != nil {
		return nil, err
	}

	if err := svc.RunHooks(ctx, runtime.ActionCreate, req, m); err != nil {
		return nil, err
	}

	res, err := runtime.WrapResult(WrapProtoGroup(m.Save(ctx)))
	if err != nil {
		return nil, err
	}
	if err := svc.RunHooksAfter(ctx, runtime.ActionAfterCreate, req, res); err != nil {
		return nil, err
	}
	return res, nil

}

// Get implements GroupServiceHandlerServer.Get
func (svc *GroupServiceHandler) Get(ctx context.Context, req *connect.Request[wrapperspb.Int32Value]) (*connect.Response[entpb.Group], error) {

	query := svc.Client.Group.Query()
	query = query.Where(
		group.ID(int(req.Msg.Value)),
	)

	if err := svc.RunHooks(ctx, runtime.ActionGet, req, query); err != nil {
		return nil, err
	}
	res, err := runtime.WrapResult(WrapProtoGroup(query.First(ctx)))
	if err != nil {
		return nil, err
	}
	if err := svc.RunHooksAfter(ctx, runtime.ActionAfterGet, req, res); err != nil {
		return nil, err
	}
	return res, nil

}

// Update implements GroupServiceHandlerServer.Update
func (svc *GroupServiceHandler) Update(ctx context.Context, req *connect.Request[entpb.UpdateGroupRequest]) (*connect.Response[entpb.Group], error) {
	group := req.Msg
	groupID := int(group.GetId())
	m := svc.Client.Group.UpdateOneID(groupID)
	if group.GetName() != nil {
		groupName := group.GetName().GetValue()
		m.SetName(groupName)
	}
	for _, item := range group.GetUsers() {
		users := int(item.GetId())
		m.AddUserIDs(users)
	}

	if err := svc.RunHooks(ctx, runtime.ActionUpdate, req, m); err != nil {
		return nil, err
	}

	res, err := runtime.WrapResult(WrapProtoGroup(m.Save(ctx)))
	if err != nil {
		return nil, err
	}
	if err := svc.RunHooksAfter(ctx, runtime.ActionAfterUpdate, req, res); err != nil {
		return nil, err
	}
	return res, nil

}

// Delete implements GroupServiceHandlerServer.Delete
func (svc *GroupServiceHandler) Delete(ctx context.Context, req *connect.Request[wrapperspb.Int32Value]) (*connect.Response[emptypb.Empty], error) {

	query := svc.Client.Group.DeleteOneID(int(req.Msg.Value))
	if err := svc.RunHooks(ctx, runtime.ActionDelete, req, query); err != nil {
		return nil, err
	}

	if err := query.Exec(ctx); err != nil {
		return nil, wrapError(err)
	}

	res := connect.NewResponse(&emptypb.Empty{})
	if err := svc.RunHooksAfter(ctx, runtime.ActionAfterDelete, req, res); err != nil {
		return nil, err
	}
	return res, nil

}

// List implements GroupServiceHandlerServer.List
func (svc *GroupServiceHandler) List(ctx context.Context, req *connect.Request[entpb.ListGroupRequest]) (*connect.Response[entpb.ListGroupResponse], error) {

	query, totalQuery, err := svc.BuildListQuery(ctx, req)

	if err != nil {
		return nil, wrapError(err)
	}

	items, err := WrapProtoGroupList(query.All(ctx))
	if err != nil {
		return nil, wrapError(err)
	}
	total, err := totalQuery.Count(ctx)
	if err != nil {
		return nil, wrapError(err)
	}

	res := connect.NewResponse(&entpb.ListGroupResponse{
		Items: items,
		Total: int32(total),
	})
	if err := svc.RunHooksAfter(ctx, runtime.ActionAfterList, req, res); err != nil {
		return nil, err
	}
	return res, nil

}

// List implements GroupServiceHandlerServer.List
func (svc *GroupServiceHandler) BuildListQuery(ctx context.Context, req *connect.Request[entpb.ListGroupRequest]) (*ent.GroupQuery, *ent.GroupQuery, error) {

	snake := gen.Funcs["snake"].(func(string) string)

	query := svc.Client.Group.Query()
	totalQuery := svc.Client.Group.Query()

	if !req.Msg.NoLimit {
		if req.Msg.Limit != nil && req.Msg.Limit.Value > 0 {
			query = query.Limit(int(req.Msg.Limit.Value))
		} else { // If no limit, set default limit
			query = query.Limit(10)
		}
	}
	if req.Msg.Offset != nil {
		query = query.Offset(int(req.Msg.Offset.Value))
	}
	if req.Msg.Order != nil {
		OrderFunc := ent.Asc
		if req.Msg.Descending {
			OrderFunc = ent.Desc
		}
		query = query.Order(OrderFunc(snake(req.Msg.Order.Value)))
	} else {
		query = query.Order(ent.Asc("id"))
	}

	if req.Msg.Filter != nil {
	}

	if err := svc.RunHooks(ctx, runtime.ActionList, req, query); err != nil {
		return nil, nil, err
	}
	if err := svc.RunHooks(ctx, runtime.ActionListCount, req, totalQuery); err != nil {
		return nil, nil, err
	}

	return query, totalQuery, nil

}

func (svc *GroupServiceHandler) createBuilder(group *entpb.Group) (*ent.GroupCreate, error) {
	m := svc.Client.Group.Create()
	groupName := group.GetName()
	m.SetName(groupName)
	for _, item := range group.GetUsers() {
		users := int(item.GetId())
		m.AddUserIDs(users)
	}
	return m, nil
}
