// Code generated by protoc-gen-entgrpc. DO NOT EDIT.
package entpbservice

import (
	connect "connectrpc.com/connect"
	context "context"
	gen "entgo.io/ent/entc/gen"
	runtime "github.com/yoshino-s/entproto/runtime"
	ent "github.com/yoshino-s/entproto/test/ent"
	project "github.com/yoshino-s/entproto/test/ent/project"
	entpb "github.com/yoshino-s/entproto/test/proto/entpb"
	entpbconnect "github.com/yoshino-s/entproto/test/proto/entpb/entpbconnect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// ProjectService implements $connectHandler
type ProjectService struct {
	*runtime.BaseService
	*ent.Client
}

var _ entpbconnect.ProjectServiceHandler = (*ProjectService)(nil)

// NewProjectService returns a new ProjectService
func NewProjectService(client *ent.Client) *ProjectService {
	return &ProjectService{
		BaseService: runtime.NewBaseService(),
		Client:      client,
	}
}

// Create implements ProjectServiceServer.Create
func (svc *ProjectService) Create(ctx context.Context, req *connect.Request[entpb.Project]) (*connect.Response[entpb.Project], error) {
	project := req.Msg
	m, err := svc.createBuilder(project)
	if err != nil {
		return nil, err
	}

	if err := svc.RunHooks(ctx, runtime.ActionCreate, req, m); err != nil {
		return nil, err
	}

	return runtime.WrapResult(WrapProtoProject(m.Save(ctx)))

}

// Get implements ProjectServiceServer.Get
func (svc *ProjectService) Get(ctx context.Context, req *connect.Request[wrapperspb.Int32Value]) (*connect.Response[entpb.Project], error) {

	query := svc.Client.Project.Query()
	query = query.Where(
		project.ID(int(req.Msg.Value)),
	)

	if err := svc.RunHooks(ctx, runtime.ActionGet, req, query); err != nil {
		return nil, err
	}
	return runtime.WrapResult(WrapProtoProject(query.First(ctx)))

}

// Update implements ProjectServiceServer.Update
func (svc *ProjectService) Update(ctx context.Context, req *connect.Request[entpb.Project]) (*connect.Response[entpb.Project], error) {
	project := req.Msg
	projectID := int(project.GetId())
	m := svc.Client.Project.UpdateOneID(projectID)
	if project.GetDescription() != nil {
		projectDescription := project.GetDescription().GetValue()
		m.SetDescription(projectDescription)
	}
	projectName := project.GetName()
	m.SetName(projectName)
	if project.GetUpdatedAt() != nil {
		projectUpdatedAt := runtime.ExtractTime(project.GetUpdatedAt())
		m.SetUpdatedAt(projectUpdatedAt)
	}
	for _, item := range project.GetTasks() {
		tasks := int(item.GetId())
		m.AddTaskIDs(tasks)
	}

	if err := svc.RunHooks(ctx, runtime.ActionUpdate, req, m); err != nil {
		return nil, err
	}

	return runtime.WrapResult(WrapProtoProject(m.Save(ctx)))

}

// Delete implements ProjectServiceServer.Delete
func (svc *ProjectService) Delete(ctx context.Context, req *connect.Request[wrapperspb.Int32Value]) (*connect.Response[emptypb.Empty], error) {

	query := svc.Client.Project.DeleteOneID(int(req.Msg.Value))
	if err := svc.RunHooks(ctx, runtime.ActionDelete, req, query); err != nil {
		return nil, err
	}

	if err := query.Exec(ctx); err != nil {
		return nil, wrapError(err)
	}
	return connect.NewResponse(&emptypb.Empty{}), nil

}

// List implements ProjectServiceServer.List
func (svc *ProjectService) List(ctx context.Context, req *connect.Request[entpb.ListProjectRequest]) (*connect.Response[entpb.ListProjectResponse], error) {

	query, totalQuery, err := svc.BuildListQuery(req)
	if err := svc.RunHooks(ctx, runtime.ActionList, req, query); err != nil {
		return nil, err
	}
	if err := svc.RunHooks(ctx, runtime.ActionListCount, req, totalQuery); err != nil {
		return nil, err
	}

	if err != nil {
		return nil, wrapError(err)
	}

	items, err := WrapProtoProjectList(query.All(ctx))
	if err != nil {
		return nil, wrapError(err)
	}
	total, err := totalQuery.Count(ctx)
	if err != nil {
		return nil, wrapError(err)
	}

	return connect.NewResponse(&entpb.ListProjectResponse{
		Items: items,
		Total: int32(total),
	}), nil

}

// List implements ProjectServiceServer.List
func (svc *ProjectService) BuildListQuery(req *connect.Request[entpb.ListProjectRequest]) (*ent.ProjectQuery, *ent.ProjectQuery, error) {

	snake := gen.Funcs["snake"].(func(string) string)

	query := svc.Client.Project.Query()
	totalQuery := svc.Client.Project.Query()

	if req.Msg.Limit != nil && req.Msg.Limit.Value > 0 {
		query = query.Limit(int(req.Msg.Limit.Value))
	} else { // If no limit, set default limit
		query = query.Limit(10)
	}
	if req.Msg.Offset != nil {
		query = query.Offset(int(req.Msg.Offset.Value))
	}
	if req.Msg.Order != nil {
		OrderFunc := ent.Asc
		if req.Msg.Descending {
			OrderFunc = ent.Desc
		}
		query = query.Order(OrderFunc(snake(req.Msg.Order.Value)))
	}

	if req.Msg.Filter != nil {

		if req.Msg.Filter.GetNameContains() != nil {
			filterNameContains := req.Msg.Filter.GetNameContains().GetValue()
			query = query.Where(project.NameContains(filterNameContains))
			totalQuery = totalQuery.Where(project.NameContains(filterNameContains))
		}
	}

	return query, totalQuery, nil

}

func (svc *ProjectService) createBuilder(project *entpb.Project) (*ent.ProjectCreate, error) {
	m := svc.Client.Project.Create()
	if project.GetCreatedAt() != nil {
		projectCreatedAt := runtime.ExtractTime(project.GetCreatedAt())
		m.SetCreatedAt(projectCreatedAt)
	}
	if project.GetDescription() != nil {
		projectDescription := project.GetDescription().GetValue()
		m.SetDescription(projectDescription)
	}
	projectName := project.GetName()
	m.SetName(projectName)
	if project.GetUpdatedAt() != nil {
		projectUpdatedAt := runtime.ExtractTime(project.GetUpdatedAt())
		m.SetUpdatedAt(projectUpdatedAt)
	}
	for _, item := range project.GetTasks() {
		tasks := int(item.GetId())
		m.AddTaskIDs(tasks)
	}
	return m, nil
}
