// Code generated by protoc-gen-entgrpc. DO NOT EDIT.
package entpbservice

import (
	connect "connectrpc.com/connect"
	context "context"
	gen "entgo.io/ent/entc/gen"
	runtime "github.com/yoshino-s/entproto/runtime"
	ent "github.com/yoshino-s/entproto/test/ent"
	tagcategory "github.com/yoshino-s/entproto/test/ent/tagcategory"
	entpb "github.com/yoshino-s/entproto/test/proto/entpb"
	entpbconnect "github.com/yoshino-s/entproto/test/proto/entpb/entpbconnect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// TagCategoryService implements $connectHandler
type TagCategoryService struct {
	*runtime.BaseService
	*ent.Client
}

var _ entpbconnect.TagCategoryServiceHandler = (*TagCategoryService)(nil)

// NewTagCategoryService returns a new TagCategoryService
func NewTagCategoryService(client *ent.Client) *TagCategoryService {
	return &TagCategoryService{
		BaseService: runtime.NewBaseService(),
		Client:      client,
	}
}

// Create implements TagCategoryServiceServer.Create
func (svc *TagCategoryService) Create(ctx context.Context, req *connect.Request[entpb.TagCategory]) (*connect.Response[entpb.TagCategory], error) {
	tagcategory := req.Msg
	m, err := svc.createBuilder(tagcategory)
	if err != nil {
		return nil, err
	}

	if err := svc.RunHooks(ctx, runtime.ActionCreate, req, m); err != nil {
		return nil, err
	}

	return runtime.WrapResult(WrapProtoTagCategory(m.Save(ctx)))

}

// Get implements TagCategoryServiceServer.Get
func (svc *TagCategoryService) Get(ctx context.Context, req *connect.Request[wrapperspb.Int32Value]) (*connect.Response[entpb.TagCategory], error) {

	query := svc.Client.TagCategory.Query()
	query = query.Where(
		tagcategory.ID(int(req.Msg.Value)),
	)

	if err := svc.RunHooks(ctx, runtime.ActionGet, req, query); err != nil {
		return nil, err
	}
	return runtime.WrapResult(WrapProtoTagCategory(query.First(ctx)))

}

// Update implements TagCategoryServiceServer.Update
func (svc *TagCategoryService) Update(ctx context.Context, req *connect.Request[entpb.TagCategory]) (*connect.Response[entpb.TagCategory], error) {
	tagcategory := req.Msg
	tagcategoryID := int(tagcategory.GetId())
	m := svc.Client.TagCategory.UpdateOneID(tagcategoryID)
	if tagcategory.GetDescription() != nil {
		tagcategoryDescription := tagcategory.GetDescription().GetValue()
		m.SetDescription(tagcategoryDescription)
	}
	tagcategoryName := tagcategory.GetName()
	m.SetName(tagcategoryName)
	tagcategoryType := toEntTagCategory_Type(tagcategory.GetType())
	m.SetType(tagcategoryType)
	if tagcategory.GetUpdatedAt() != nil {
		tagcategoryUpdatedAt := runtime.ExtractTime(tagcategory.GetUpdatedAt())
		m.SetUpdatedAt(tagcategoryUpdatedAt)
	}

	if err := svc.RunHooks(ctx, runtime.ActionUpdate, req, m); err != nil {
		return nil, err
	}

	return runtime.WrapResult(WrapProtoTagCategory(m.Save(ctx)))

}

// Delete implements TagCategoryServiceServer.Delete
func (svc *TagCategoryService) Delete(ctx context.Context, req *connect.Request[wrapperspb.Int32Value]) (*connect.Response[emptypb.Empty], error) {

	query := svc.Client.TagCategory.DeleteOneID(int(req.Msg.Value))
	if err := svc.RunHooks(ctx, runtime.ActionDelete, req, query); err != nil {
		return nil, err
	}

	if err := query.Exec(ctx); err != nil {
		return nil, wrapError(err)
	}
	return connect.NewResponse(&emptypb.Empty{}), nil

}

// List implements TagCategoryServiceServer.List
func (svc *TagCategoryService) List(ctx context.Context, req *connect.Request[entpb.ListTagCategoryRequest]) (*connect.Response[entpb.ListTagCategoryResponse], error) {

	query, totalQuery, err := svc.BuildListQuery(req)
	if err := svc.RunHooks(ctx, runtime.ActionList, req, query); err != nil {
		return nil, err
	}
	if err := svc.RunHooks(ctx, runtime.ActionListCount, req, totalQuery); err != nil {
		return nil, err
	}

	if err != nil {
		return nil, wrapError(err)
	}

	items, err := WrapProtoTagCategoryList(query.All(ctx))
	if err != nil {
		return nil, wrapError(err)
	}
	total, err := totalQuery.Count(ctx)
	if err != nil {
		return nil, wrapError(err)
	}

	return connect.NewResponse(&entpb.ListTagCategoryResponse{
		Items: items,
		Total: int32(total),
	}), nil

}

// List implements TagCategoryServiceServer.List
func (svc *TagCategoryService) BuildListQuery(req *connect.Request[entpb.ListTagCategoryRequest]) (*ent.TagCategoryQuery, *ent.TagCategoryQuery, error) {

	snake := gen.Funcs["snake"].(func(string) string)

	query := svc.Client.TagCategory.Query()
	totalQuery := svc.Client.TagCategory.Query()

	if req.Msg.Limit != nil && req.Msg.Limit.Value > 0 {
		query = query.Limit(int(req.Msg.Limit.Value))
	} else { // If no limit, set default limit
		query = query.Limit(10)
	}
	if req.Msg.Offset != nil {
		query = query.Offset(int(req.Msg.Offset.Value))
	}
	if req.Msg.Order != nil {
		OrderFunc := ent.Asc
		if req.Msg.Descending {
			OrderFunc = ent.Desc
		}
		query = query.Order(OrderFunc(snake(req.Msg.Order.Value)))
	}

	if req.Msg.Filter != nil {

		filterType := toEntTagCategory_Type(req.Msg.Filter.GetType())
		query = query.Where(tagcategory.TypeEQ(filterType))
		totalQuery = totalQuery.Where(tagcategory.TypeEQ(filterType))
	}

	return query, totalQuery, nil

}

func (svc *TagCategoryService) createBuilder(tagcategory *entpb.TagCategory) (*ent.TagCategoryCreate, error) {
	m := svc.Client.TagCategory.Create()
	if tagcategory.GetCreatedAt() != nil {
		tagcategoryCreatedAt := runtime.ExtractTime(tagcategory.GetCreatedAt())
		m.SetCreatedAt(tagcategoryCreatedAt)
	}
	if tagcategory.GetDescription() != nil {
		tagcategoryDescription := tagcategory.GetDescription().GetValue()
		m.SetDescription(tagcategoryDescription)
	}
	tagcategoryName := tagcategory.GetName()
	m.SetName(tagcategoryName)
	tagcategoryType := toEntTagCategory_Type(tagcategory.GetType())
	m.SetType(tagcategoryType)
	if tagcategory.GetUpdatedAt() != nil {
		tagcategoryUpdatedAt := runtime.ExtractTime(tagcategory.GetUpdatedAt())
		m.SetUpdatedAt(tagcategoryUpdatedAt)
	}
	return m, nil
}
