// Code generated by protoc-gen-entgrpc. DO NOT EDIT.
package entpbservice

import (
	connect "connectrpc.com/connect"
	sqlgraph "entgo.io/ent/dialect/sql/sqlgraph"
	errors "github.com/go-errors/errors"
	ent "github.com/yoshino-s/entproto/test/ent"
	entpb "github.com/yoshino-s/entproto/test/proto/entpb"
)

// ToProtoUser transforms the ent type to the pb type
func ToProtoUser(e *ent.User) (*entpb.User, error) {
	v := &entpb.User{}
	id := int32(e.ID)
	v.Id = id
	name := e.Name
	v.Name = name
	return v, nil
}

func WrapProtoUser(e *ent.User, err error) (*entpb.User, error) {
	switch {
	case err == nil:
		return ToProtoUser(e)
	case ent.IsNotFound(err):
		return nil, connect.NewError(connect.CodeNotFound, errors.Errorf("not found: %s", err))
	case sqlgraph.IsUniqueConstraintError(err):
		return nil, connect.NewError(connect.CodeAlreadyExists, errors.Errorf("already exists: %s", err))
	case ent.IsConstraintError(err):
		return nil, connect.NewError(connect.CodeInvalidArgument, errors.Errorf("invalid argument: %s", err))
	default:
		return nil, connect.NewError(connect.CodeInternal, errors.Errorf("internal error: %s", err))
	}
}

// ToProtoUserList transforms a list of ent type to a list of pb type
func ToProtoUserList(e []*ent.User) ([]*entpb.User, error) {
	var pbList []*entpb.User
	for _, entEntity := range e {
		pbEntity, err := ToProtoUser(entEntity)
		if err != nil {
			return nil, connect.NewError(connect.CodeInternal, errors.Errorf("internal error: %s", err))
		}
		pbList = append(pbList, pbEntity)
	}
	return pbList, nil
}

func WrapProtoUserList(e []*ent.User, err error) ([]*entpb.User, error) {
	switch {
	case err == nil:
		return ToProtoUserList(e)
	case ent.IsNotFound(err):
		return nil, connect.NewError(connect.CodeNotFound, errors.Errorf("not found: %s", err))
	case sqlgraph.IsUniqueConstraintError(err):
		return nil, connect.NewError(connect.CodeAlreadyExists, errors.Errorf("already exists: %s", err))
	case ent.IsConstraintError(err):
		return nil, connect.NewError(connect.CodeInvalidArgument, errors.Errorf("invalid argument: %s", err))
	default:
		return nil, connect.NewError(connect.CodeInternal, errors.Errorf("internal error: %s", err))
	}
}
